module.exports = {
    USER_EXIST: 'USER WITH THIS EMAIL EXIST, PLEASE INPUT ANOTHER EMAIL',
    ADD_USER: 'USER IS ADDED ',
    UPDATE_USER: 'USER IS UPDATED!',
    ACCESS_DENIED: 'ACCCESS IS DANIED',
    USER_ID_VALID: 'WRONG USER ID FORMAT',
    PASSWORD_INVALID: 'THE PASSWORD MUST HAVE AT LEAST ONE LETTER AND NUMBER, AND MUST BE ATLEAST 8 CHARACTERS LONG',
    INVALID_EMAIL: 'EMAIL FORMAT IS INVALID',
    WRONG_TEMPLATE_NAME: 'WRONG TAMPLATE NAME',
    USERNAME_UNIQUE: 'USER WITH THIS USERNAME EXIST, PLEASE INPUT ANOTHER USERNAME'

};
